CREATE TABLE `history` (
	`TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DEVICE` VARCHAR(64) NULL DEFAULT NULL,
	`TYPE` VARCHAR(64) NULL DEFAULT NULL,
	`EVENT` VARCHAR(512) NULL DEFAULT NULL,
	`READING` VARCHAR(64) NULL DEFAULT NULL,
	`VALUE` VARCHAR(128) NULL DEFAULT NULL,
	`UNIT` VARCHAR(32) NULL DEFAULT NULL,
	INDEX `Search_Idx` (`DEVICE`, `READING`, `TIMESTAMP`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `current` (
	`TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`DEVICE` VARCHAR(64) NULL DEFAULT NULL,
	`TYPE` VARCHAR(64) NULL DEFAULT NULL,
	`EVENT` VARCHAR(512) NULL DEFAULT NULL,
	`READING` VARCHAR(64) NULL DEFAULT NULL,
	`VALUE` VARCHAR(128) NULL DEFAULT NULL,
	`UNIT` VARCHAR(32) NULL DEFAULT NULL,
	INDEX `searchkey` (`DEVICE`, `READING`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
